# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_aux <- function(ref_n, n, X, K, given_kern, CrossKern, p, s2_i, alpha, use_tested_inlier, rnormmat) {
    .Call(`_RaPKod_Rcpp_aux`, ref_n, n, X, K, given_kern, CrossKern, p, s2_i, alpha, use_tested_inlier, rnormmat)
}

